version: "3"
services:
  app:
    container_name: effectiveOfficeBackend
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db_postgres:
        condition: service_healthy
    environment:
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: "db_postgres"            # The name of the service in the same network
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PORT: "5432"
      DATABASE_NAME: ${POSTGRES_DB}
      VERIFICATION_PLUGIN_ENABLE: ${VERIFICATION_PLUGIN_ENABLE}
      MIGRATIONS_ENABLE: ${MIGRATIONS_ENABLE}
      SERVICE_ACCOUNT_KEY_PATH: ${SERVICE_ACCOUNT_KEY_PATH}
      JSON_GOOGLE_CREDENTIALS: ${JSON_GOOGLE_CREDENTIALS}

  db_postgres:
    container_name: postgresForKtor
    image: postgres:15.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "15432:5432"
    restart: "always"
    healthcheck:
       test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
       interval: 1s
       timeout: 5s
       retries: 10


volumes:
  pgdata: {}
